"""Clinical diagnostic catalog used by the HMS catalog and seed routines.

The catalog is deliberately data-driven: numeric laboratory tests expose result
parameters, while interpreted studies expose structured observations. Reference
ranges are not kept here because they must be validated by each laboratory,
method, analyser, age and sex before clinical use.
"""


def test(code, category, subcategory, name, approver, parameters, specimen=None,
         report_type="Structured parameters"):
    return {
        "code": code, "category": category, "subcategory": subcategory,
        "name": name, "approving_specialty": approver,
        "parameters": parameters, "specimen": specimen,
        "report_type": report_type,
    }


DIAGNOSTIC_CATALOG = [
    test("HEM-CBC", "Laboratory", "Hematology", "Complete Blood Count (CBC)", "Pathology / Laboratory Medicine", ["Hemoglobin", "RBC", "WBC", "Platelets", "Hematocrit", "MCV", "MCH", "MCHC", "RDW"], "EDTA whole blood"),
    test("HEM-CBCD", "Laboratory", "Hematology", "CBC with Differential", "Pathology / Laboratory Medicine", ["Neutrophils", "Lymphocytes", "Monocytes", "Eosinophils", "Basophils"], "EDTA whole blood"),
    test("HEM-ESR", "Laboratory", "Hematology", "ESR", "Pathology / Laboratory Medicine", ["ESR"], "EDTA/citrate whole blood"),
    test("HEM-RETIC", "Laboratory", "Hematology", "Reticulocyte Count", "Pathology / Laboratory Medicine", ["Reticulocyte %", "Absolute reticulocyte count"], "EDTA whole blood"),
    test("HEM-SMEAR", "Laboratory", "Hematology", "Peripheral Blood Smear", "Pathologist", ["RBC morphology", "WBC morphology", "Platelet morphology"], "EDTA whole blood", "Narrative and structured observations"),
    test("COAG-PROFILE", "Laboratory", "Coagulation", "Coagulation Profile", "Pathology / Laboratory Medicine", ["PT", "INR", "aPTT", "Fibrinogen", "D-Dimer"], "Citrate plasma"),
    test("CHEM-RFT", "Laboratory", "Clinical Biochemistry", "Renal Function Test", "Pathology / Laboratory Medicine", ["Creatinine", "Urea", "BUN", "eGFR", "Uric acid"], "Serum/plasma"),
    test("CHEM-ELECT", "Laboratory", "Clinical Biochemistry", "Electrolyte Panel", "Pathology / Laboratory Medicine", ["Sodium", "Potassium", "Chloride", "Bicarbonate", "Calcium", "Magnesium", "Phosphorus"], "Serum/plasma"),
    test("CHEM-LFT", "Laboratory", "Clinical Biochemistry", "Liver Function Test", "Pathology / Laboratory Medicine", ["Total bilirubin", "Direct bilirubin", "Indirect bilirubin", "AST", "ALT", "ALP", "GGT", "Total protein", "Albumin", "Globulin", "A/G ratio"], "Serum"),
    test("CHEM-DIAB", "Laboratory", "Diabetes", "Diabetes Profile", "Pathology / Laboratory Medicine", ["Fasting glucose", "Random glucose", "Post-prandial glucose", "HbA1c", "Estimated average glucose"], "Blood"),
    test("CHEM-GTT", "Laboratory", "Diabetes", "Glucose Tolerance Test", "Pathology / Laboratory Medicine", ["Fasting glucose", "1-hour glucose", "2-hour glucose"], "Plasma"),
    test("CHEM-LIPID", "Laboratory", "Lipid Studies", "Lipid Profile", "Pathology / Laboratory Medicine", ["Total cholesterol", "LDL", "HDL", "Triglycerides", "VLDL", "Apo-A1", "Apo-B", "Lp(a)"], "Serum"),
    test("CARD-MARKER", "Laboratory", "Cardiac Markers", "Cardiac Biomarker Panel", "Pathology / Laboratory Medicine", ["Troponin I/T", "CK-MB", "Total CK", "BNP", "NT-proBNP"], "Serum/plasma"),
    test("NUTRIENT", "Laboratory", "Vitamins and Nutrition", "Vitamin and Mineral Profile", "Pathology / Laboratory Medicine", ["25-OH vitamin D", "Vitamin B12", "Folate", "Iron", "TIBC", "Transferrin", "Transferrin saturation", "Ferritin", "Zinc", "Copper"], "Serum"),
    test("ENDO-THY", "Laboratory", "Endocrinology", "Thyroid Profile", "Pathology / Laboratory Medicine", ["TSH", "T3", "T4", "FT3", "FT4", "Anti-TPO", "Anti-Tg", "Thyroglobulin"], "Serum"),
    test("ENDO-REPRO", "Laboratory", "Endocrinology", "Reproductive Hormone Profile", "Pathology / Laboratory Medicine", ["FSH", "LH", "Estradiol", "Progesterone", "Testosterone", "Free testosterone", "SHBG", "Prolactin", "AMH", "beta-hCG"], "Serum"),
    test("ENDO-ADRENAL", "Laboratory", "Endocrinology", "Adrenal Hormone Profile", "Pathology / Laboratory Medicine", ["Cortisol", "ACTH", "Aldosterone", "Renin"], "Blood"),
    test("ENDO-METAB", "Laboratory", "Endocrinology", "Metabolic Hormone Profile", "Pathology / Laboratory Medicine", ["Insulin", "C-peptide", "Growth hormone", "IGF-1", "PTH"], "Serum/plasma"),
    test("URINE-RME", "Laboratory", "Urinalysis", "Routine Urinalysis", "Pathology / Laboratory Medicine", ["Color", "Appearance", "Specific gravity", "pH", "Protein", "Glucose", "Ketones", "Bilirubin", "Urobilinogen", "Blood", "Nitrite", "Leukocyte esterase", "RBC", "WBC", "Epithelial cells", "Casts", "Crystals", "Bacteria", "Yeast", "Mucus"], "Urine"),
    test("URINE-CULT", "Laboratory", "Microbiology", "Urine Culture and Sensitivity", "Microbiologist / Pathologist", ["Organism", "Colony count", "Antibiotic sensitivity", "Antibiotic resistance"], "Urine"),
    test("URINE-24H", "Laboratory", "Urinalysis", "24-Hour Urine Profile", "Pathology / Laboratory Medicine", ["Protein", "Creatinine clearance", "Calcium", "Sodium", "Potassium", "Urea", "Cortisol", "Metanephrines"], "24-hour urine"),
    test("STOOL-RME", "Laboratory", "Stool Studies", "Stool Routine and Microscopy", "Pathology / Laboratory Medicine", ["Color", "Consistency", "Mucus", "Blood", "Parasites", "Ova", "Cysts"], "Stool"),
    test("STOOL-GI", "Laboratory", "Stool Studies", "Gastrointestinal Stool Panel", "Microbiologist / Pathologist", ["Occult blood", "Culture organism", "Calprotectin", "C. difficile toxin/antigen", "Pancreatic elastase"], "Stool"),
    test("MICRO-CULT", "Laboratory", "Microbiology", "Culture and Antimicrobial Susceptibility", "Microbiologist / Pathologist", ["Gram stain", "Organism", "Colony count", "Antibiotic sensitivity", "Antibiotic resistance"], "Blood/urine/stool/sputum/wound/throat swab/CSF"),
    test("MICRO-VIRAL", "Laboratory", "Microbiology", "Viral Detection Panel", "Microbiologist / Pathologist", ["Antigen", "Antibody", "PCR result", "Ct value", "Viral load", "Genotype"], "Swab/blood/body fluid"),
    test("IMM-SERO", "Laboratory", "Serology and Immunology", "Infectious and Autoimmune Serology", "Pathology / Laboratory Medicine", ["HIV Ag/Ab", "HBsAg", "Anti-HBs", "Anti-HBc", "Anti-HCV", "Dengue NS1/IgM/IgG", "Malaria antigen", "RF", "Anti-CCP", "ANA", "CRP", "ASO"], "Serum/plasma"),
    test("BB-GROUP", "Laboratory", "Blood Bank", "Blood Grouping and Compatibility", "Transfusion Medicine / Pathology", ["ABO", "Rh(D)", "Patient group", "Donor group", "Compatibility", "Crossmatch result", "Direct Coombs", "Indirect Coombs", "Antibody screen", "Antibody identification"], "Blood"),
    test("GEN-MOL", "Laboratory", "Molecular and Genetics", "Molecular / Genetic Test", "Molecular Pathologist / Clinical Geneticist", ["Target organism/gene", "Detected/not detected", "Ct value", "Load", "Chromosome", "Gene", "Variant", "Genotype", "Pathogenicity"], "Blood/saliva/tissue/body fluid"),
    test("ONC-MARK", "Laboratory", "Oncology", "Tumor Marker Panel", "Pathology / Laboratory Medicine", ["PSA", "CA-125", "CEA", "CA 19-9", "AFP", "beta-hCG", "Thyroglobulin"], "Serum"),
    test("PATH-HIST", "Pathology", "Histopathology", "Biopsy / Histopathology", "Pathologist", ["Tumor type", "Grade", "Margin status", "Lymphovascular invasion", "Biomarker expression"], "Tissue", "Narrative pathology report"),
    test("PATH-CYTO", "Pathology", "Cytology", "FNAC / Cytology", "Pathologist", ["Specimen adequacy", "Cytology", "Cell abnormalities", "Diagnostic category"], "Aspirate/smear", "Narrative pathology report"),
    test("XR-CHEST", "Radiology", "X-Ray", "Chest X-Ray", "Radiologist", ["Heart size", "Lung fields", "Pleural spaces", "Costophrenic angles", "Diaphragm", "Mediastinum", "Bones", "Consolidation", "Effusion", "Pneumothorax"], report_type="Findings and impression"),
    test("XR-MSK", "Radiology", "X-Ray", "Musculoskeletal X-Ray", "Radiologist", ["Bone", "Fracture", "Alignment", "Joint space", "Bone density", "Soft tissue"], report_type="Findings and impression"),
    test("XR-OTHER", "Radiology", "X-Ray", "Other Plain Radiography", "Radiologist", ["Skull", "Spine", "Pelvis", "Hip", "Shoulder", "Elbow", "Wrist", "Hand", "Knee", "Ankle", "Foot", "Abdomen"], report_type="Findings and impression"),
    test("CT-HEAD", "Radiology", "CT", "CT Head / Brain", "Radiologist", ["Brain parenchyma", "Ventricles", "Hemorrhage", "Infarction", "Mass", "Midline shift", "Skull", "Sinuses"], report_type="Findings and impression"),
    test("CT-CHEST", "Radiology", "CT", "CT Chest", "Radiologist", ["Lung fields", "Nodules", "Consolidation", "Pleural effusion", "Mediastinum", "Lymph nodes", "Heart", "Great vessels"], report_type="Findings and impression"),
    test("CT-ABD", "Radiology", "CT", "CT Abdomen / Pelvis", "Radiologist", ["Liver", "Gallbladder", "Pancreas", "Spleen", "Kidneys", "Adrenals", "Bowel", "Bladder", "Reproductive organs", "Lymph nodes"], report_type="Findings and impression"),
    test("CT-ANGIO", "Radiology", "CT Angiography", "CT Angiography", "Radiologist", ["Vessel", "Stenosis", "Occlusion", "Aneurysm", "Thrombus", "Contrast enhancement"], report_type="Findings and impression"),
    test("MRI-BRAIN", "Radiology", "MRI", "MRI Brain", "Radiologist", ["Brain tissue", "Ventricles", "Cerebellum", "Brainstem", "Diffusion", "Hemorrhage", "Tumor", "Infarction", "White matter lesions"], report_type="Findings and impression"),
    test("MRI-SPINE", "Radiology", "MRI", "MRI Spine", "Radiologist", ["Vertebral bodies", "Discs", "Spinal cord", "Canal", "Nerve roots", "Herniation", "Stenosis"], report_type="Findings and impression"),
    test("MRI-JOINT", "Radiology", "MRI", "MRI Joint", "Radiologist", ["Bone", "Cartilage", "Ligaments", "Tendons", "Meniscus", "Joint fluid"], report_type="Findings and impression"),
    test("US-ABD", "Radiology", "Ultrasound", "Abdominal Ultrasound", "Radiologist", ["Liver", "Gallbladder", "CBD", "Pancreas", "Spleen", "Kidneys", "Bladder", "Size", "Shape", "Echogenicity", "Lesions", "Stones", "Cysts", "Fluid"], report_type="Measurements, findings and impression"),
    test("US-OB", "Radiology", "Ultrasound", "Obstetric Ultrasound", "Radiologist / Fetal Medicine Specialist", ["Gestational age", "Fetal heart rate", "CRL", "BPD", "HC", "AC", "FL", "Estimated fetal weight", "Placenta", "Amniotic fluid"], report_type="Measurements, findings and impression"),
    test("US-DOPPLER", "Radiology", "Doppler", "Doppler Ultrasound", "Radiologist", ["Flow velocity", "Resistive index", "Pulsatility index", "Peak systolic velocity", "End-diastolic velocity"], report_type="Measurements, findings and impression"),
    test("MAMMO", "Radiology", "Mammography", "Mammography", "Radiologist", ["Breast density", "Mass", "Calcification", "Asymmetry", "Architectural distortion", "BI-RADS"], report_type="Findings and impression"),
    test("CARD-ECG", "Cardiology", "Electrophysiology", "ECG / EKG", "Physician / Cardiologist", ["Heart rate", "Rhythm", "PR interval", "QRS duration", "QT", "QTc", "P wave", "QRS axis", "ST segment", "T wave"], report_type="Measurements and interpretation"),
    test("CARD-ECHO", "Cardiology", "Cardiac Imaging", "Echocardiogram", "Cardiologist", ["LVEF", "LV size", "RV size", "Chamber dimensions", "Wall thickness", "Wall motion", "Valves", "Pericardium", "Doppler flow", "Pulmonary pressure"], report_type="Measurements, findings and interpretation"),
    test("CARD-TMT", "Cardiology", "Stress Testing", "Stress Test / TMT", "Cardiologist", ["Resting HR", "Maximum HR", "Blood pressure", "Exercise duration", "METs", "ST changes", "Symptoms", "Recovery HR"], report_type="Measurements and interpretation"),
    test("CARD-HOLTER", "Cardiology", "Electrophysiology", "Holter Monitoring", "Cardiologist", ["Average HR", "Minimum HR", "Maximum HR", "Arrhythmias", "PVCs", "PACs", "Pauses", "Rhythm"], report_type="Measurements and interpretation"),
    test("CARD-ANGIO", "Cardiology", "Interventional Cardiology", "Coronary Angiography", "Interventional Cardiologist", ["Coronary artery", "Stenosis %", "Lesion location", "Occlusion", "Flow", "Collaterals"], report_type="Findings and conclusion"),
    test("PULM-PFT", "Pulmonology", "Pulmonary Function", "Pulmonary Function Test", "Pulmonologist", ["FVC", "FEV1", "FEV1/FVC", "PEFR", "FEF25-75", "TLC", "RV", "DLCO"], report_type="Measurements and interpretation"),
    test("PULM-ABG", "Pulmonology", "Blood Gas", "Arterial Blood Gas", "Pathology / Critical Care Physician", ["pH", "PaO2", "PaCO2", "HCO3", "SaO2", "Base excess", "Lactate"], "Arterial blood"),
    test("NEURO-EEG", "Neurology", "Neurophysiology", "EEG", "Neurologist", ["Background activity", "Frequency", "Amplitude", "Seizure activity"], report_type="Waveform findings and interpretation"),
    test("NEURO-EMG", "Neurology", "Neurophysiology", "EMG", "Neurologist", ["Muscle electrical activity", "Motor unit potentials", "Recruitment"], report_type="Measurements and interpretation"),
    test("NEURO-NCS", "Neurology", "Neurophysiology", "Nerve Conduction Study", "Neurologist", ["Conduction velocity", "Latency", "Amplitude", "F-wave", "H-reflex"], report_type="Measurements and interpretation"),
    test("GI-ENDO", "Gastroenterology", "Endoscopy", "Upper GI Endoscopy", "Gastroenterologist", ["Esophagus", "Stomach", "Duodenum", "Lesions", "Ulcers", "Bleeding", "Polyps"], report_type="Procedure findings and impression"),
    test("GI-COLON", "Gastroenterology", "Endoscopy", "Colonoscopy", "Gastroenterologist", ["Colon segments", "Polyps", "Ulcers", "Inflammation", "Bleeding", "Masses"], report_type="Procedure findings and impression"),
    test("GI-ERCP", "Gastroenterology", "Endoscopy", "ERCP", "Gastroenterologist", ["Bile duct", "Pancreatic duct", "Stones", "Strictures", "Obstruction"], report_type="Procedure findings and impression"),
    test("GYN-PAP", "Women's Health", "Cervical Screening", "Pap Smear", "Pathologist", ["Specimen adequacy", "Cytology", "Cell abnormalities", "HPV-related changes"], "Cervical sample", "Cytology report"),
    test("GYN-US", "Women's Health", "Gynecologic Imaging", "Gynecological Ultrasound", "Radiologist / Gynecologist", ["Uterus", "Endometrium", "Ovaries", "Follicles", "Cysts", "Fibroids"], report_type="Measurements, findings and impression"),
    test("URO-SEMEN", "Urology", "Andrology", "Semen Analysis", "Pathology / Andrology", ["Volume", "Appearance", "pH", "Concentration", "Total count", "Motility", "Progressive motility", "Morphology", "WBC"], "Semen"),
    test("URO-FLOW", "Urology", "Urodynamics", "Uroflowmetry", "Urologist", ["Maximum flow rate", "Average flow rate", "Voided volume", "Flow time"], report_type="Measurements and interpretation"),
    test("EYE-OCT", "Ophthalmology", "Retinal Imaging", "Optical Coherence Tomography", "Ophthalmologist", ["Retinal thickness", "Macular structure", "Optic nerve parameters"], report_type="Images, measurements and interpretation"),
    test("EYE-EXAM", "Ophthalmology", "Functional Testing", "Comprehensive Eye Tests", "Ophthalmologist", ["Visual acuity right/left", "Near vision", "Distance vision", "Intraocular pressure", "Fundus", "Visual field mean deviation", "Pattern deviation"], report_type="Measurements and findings"),
    test("ENT-AUDIO", "ENT", "Audiology", "Audiometry", "Audiologist / ENT Specialist", ["Air conduction", "Bone conduction", "Hearing threshold", "Speech reception threshold", "Word recognition"], report_type="Audiogram and interpretation"),
    test("ENT-TYMP", "ENT", "Audiology", "Tympanometry", "Audiologist / ENT Specialist", ["Ear canal volume", "Middle-ear pressure", "Compliance"], report_type="Measurements and interpretation"),
    test("ALLERGY", "Allergy", "Allergy Testing", "Allergy Test Panel", "Allergist / Pathology", ["Total IgE", "Specific IgE", "Allergen", "Reaction size", "Positive/negative"], "Blood or skin test"),
    test("BONE-DEXA", "Musculoskeletal", "Bone Density", "DEXA Scan", "Radiologist / Endocrinologist", ["BMD", "T-score", "Z-score"], report_type="Measurements and interpretation"),
    test("NM-PETCT", "Nuclear Medicine", "PET", "PET / PET-CT", "Nuclear Medicine Physician / Radiologist", ["Uptake", "Distribution", "Lesion activity", "SUV", "Perfusion"], report_type="Findings and impression"),
    test("NM-ORGAN", "Nuclear Medicine", "Scintigraphy", "Organ Nuclear Medicine Scan", "Nuclear Medicine Physician", ["Uptake", "Distribution", "Organ function", "Perfusion"], report_type="Findings and impression"),
    test("DENTAL-XR", "Dental", "Dental Imaging", "Dental X-Ray / OPG / CBCT", "Dentist / Oral Radiologist", ["Teeth", "Roots", "Bone", "Jaw", "Periodontal structures", "Lesions"], report_type="Findings and impression"),
    test("PRENATAL-GEN", "Genetics", "Prenatal Testing", "Prenatal Genetic Testing", "Clinical Geneticist / Maternal-Fetal Medicine", ["Chromosome", "Gene", "Variant", "Genotype", "Pathogenicity", "Fetal fraction"], "Maternal blood/amniotic fluid/CVS"),
]

